{{- if .Values.ingress.enabled -}}
{{- $pathtype := .Values.ingress.pathtype -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ph-ee-dpg-operations-app
  labels:
    app: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}    
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className | quote }}
  {{- end }}
{{- if .Values.ingress.tls }}
  tls:
  {{- if .ingressPath }}
  {{- range  .Values.ingress.tls }}
  - hosts:
    {{- range  .hosts }}
      - {{ . }}
    {{- end }}
    secretName: {{ .secretName }}
  {{- end }}
{{- else }}
{{ toYaml .Values.ingress.tls | indent 4 }}
  {{- end }}
{{- end}}
  rules:
  {{- range .Values.ingress.hosts }}
  - host: {{ .host }}
    http:
      paths:
      {{- range .paths }}
      - path: {{ .path }}
        pathType: {{ $pathtype }}
        backend:
          service:
            name: {{ .backend.service.name}}
            port:
              number: {{ .backend.service.port.number}}
      {{- end }}
 {{- end }}
 {{- end }}
