{{- if .Values.enabled -}}
apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: operations-app-secret
type: Opaque
data:
  database-password: {{ .Values.datasource.password | b64enc }}
{{- end }}  