apiVersion: v2
name: ph-ee-superset-release
description: PaymentHub EE Barebone Edition

type: application
version: 1.0.0
appVersion: 1.16.0

dependencies:
- name: ph-ee-superset
  repository: "file://../superset"
  version: 0.2.0

  
