ph-ee-g2psandbox:
  ph-ee-engine:
    importer_es:
      enabled: false
    ph_ee_connector_ams_mifos:
      enabled: false
    crm:
      enabled: false
    billPay:
      enabled: false
    connector_bulk:
      enabled: false
    ph-ee-connector:
      enabled: false
    ph_ee_connector_gsma:
      enabled: false
    ph_ee_connector_mojaloop:
      enabled: false
    vouchers:
      enabled: false
    importer_rdbms:
      enabled: false
    importer_es:
      enabled: false
    mockpayment:
      enabled: false
    post_installation_job:
      enabled: false
    kibana:
      enabled: false
    kafka:
      global:
        storageClass: standard
      provisioning:
        enabled: false
    messagegateway:
      enabled: false
    notifications:
        enabled: false
    operations_web:
      enabled: false
    elasticsearch:
      enabled: false
      volumeClaimTemplate:
        storageClassName: standard

