ph-ee-g2psandbox:
  ph-ee-engine:
   
    zeebe-cluster-helm:
      enabled: true

      elasticsearch:
        enabled: false
      kibana:
        enabled: true

    zeebe-operate-helm:
      ingress:
        enabled: true 
        host: operate.sandbox.fynarfin.io 
      
    kibana:
      ingress:
        enabled: true
        className: "nginx"
        pathtype: "Prefix"
        annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
        hosts:
          - host: analytics.sandbox.fynarfin.io
            paths:
              - path: /

    operations:
      
    ph_ee_connector_ams_mifos:
      enabled: true
      imageTag: v1.2.2 
      deployment:
        annotations:
          rollme: '{{ randAlphaNum 5 | quote }}'
      ams_local_interop_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_account_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_customer_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_auth_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_loan_host: "https://fynams.sandbox.fynarfin.io/"
      ingress:
        enabled: true 
        hosts:
          - host: ams-mifos.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: ph-ee-connector-ams-mifos
                  port:
                    number: 80
          - host: ams-mifos-mock.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: ph-ee-connector-ams-mifos
                    port:
                      number: 7070

    ph_ee_connector_mojaloop:
      enabled: true
      imageTag: "830df54849"
      ingress:
        enabled: true
        tls:
          - secretName: fyn-cert
        hosts:
          - host: mojaloop.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: ph-ee-connector-mojaloop-java
                  port:
                    number: 80

    # kafka:

    channel:
      enabled: true
      operations:
        url: "http://ops-bk.sandbox.fynarfin.io/api/v1"
      server:
        ssl:
          keyPassword: "password"
          keyStorePassword: "password"   
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      service:
        annotations:
          konghq.com/protocol: "https"
      ingress:
        enabled: true 
        className: "kong"
        hosts:
          - host: channel.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-channel"
                  port:
                    number: 8443
          - host: channel-gsma.sandbox.fynarfin.io          
            paths:          
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-channel-gsma"
                  port:
                    number: 82  
             

    operations_app:
      enabled: true
      tenants: "rhino,gorilla"
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      ingress:
        enabled: true 
        hosts:
          - host: ops-bk.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-operations-app"
                  port:
                    number: 80 

    operations_web:
      enabled: true 
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: ops.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-operations-web"
                  port:
                    number: 4200            

    ph_ee_connector_gsma:
      enabled: true
      ingress:
        enabled: true  

    ph_ee_connector_slcb:
      enabled: false
    
    mpesa:
      enabled: false
      
    roster_connector:
      enabled: false
      
    paygops_connector:
      enabled: false
      
    notifications:
      enabled: true
      NOTIFICATION_FAILURE_ENABLED: "false"
      ingress:
        enabled: true 
        hosts:
          - host: notifications.sandbox.fynarfin.io         
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-notifications"
                  port:
                    number: 80 


    connector_bulk:
      enabled: true
      tenants: "rhino,gorilla"
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      aws:
        region: "ap-south-1"
        access_key: "aws-access-key"
        secret_key: "aws-secret-key"
      operations_app:
        contactpoint: "https://ops-bk.sandbox.fynarfin.io/"
        endpoints:
          batch_transaction: "/api/v1/batch/transactions"
      identity_account_mapper:
        hostname: "https://identity-mapper.sandbox.fynarfin.io"
      ingress:
        enabled: true
        className: "kong"
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: bulk-connector.sandbox.fynarfin.io     
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-bulk"
                  port:
                    number: 80      
          
    zeebe_ops:
      enabled: true
      tenants: "rhino,gorilla"
      ingress:
        enabled: true 
        hosts:
          - host: zeebeops.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-zeebe-ops"
                  port:
                    number: 80

    messagegateway:
      enabled: true
      secret:
        value:
          api_key: "eKiC1_JWdKy7eaTGQFHxXXjXjacr60W9Zntl"
          project_id: "PJ5ff552ce01d2978c"
      ingress:
        enabled: true   
        hosts:
          - host: messagegateway.sandbox.fynarfin.io       
            paths: 
            - path: "/"
              backend:
                service:
                  name: "message-gateway"
                  port:
                    number: 80
                            
    importer_es:
      enabled: true

    importer_rdbms:
      enabled: true
      aws:
        region: "ap-south-1"
    
    mockpayment:
      enabled: true
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: mockpaymentschema.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-connector-mock-payment-schema"
                    port:
                      number: 8080

    wildcardhostname: "*.sandbox.fynarfin.io"
    tls: ""

    keycloak:
      enabled: false
      ingress:
        enabled: true 
        rules:
          - host: 'keycloak.sandbox.fynarfin.io'
            paths:
            - path: /
              pathType: Prefix

    
    kong:
      enabled: false
      ingress:
        enabled: true
        hostname: admin-kong.sandbox.fynarfin.io 

    redis:
      enabled: true
      replica:
        replicaCount: 0

    vouchers:
      enabled: true

      voucher:
        hostname: "https://vouchers.sandbox.fynarfin.io"

      salting:
        enabled: true

      identity-account-mapper:
        hostname: "https://identity-mapper.sandbox.fynarfin.io"
      operations:
        hostname: "https://ops-bk.sandbox.fynarfin.io"
        endpoints:
          transfers: "/api/v1/transfers?size=1&page=0"

      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: vouchers.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-vouchers"
                    port:
                      number: 80


  account_mapper:
    enabled: true
    deployment:
      annotations:
        rollme: "{{ randAlphaNum 5 | quote }}"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        - secretName: sandbox-secret
      hosts:
        - host: identity-mapper.sandbox.fynarfin.io
          paths:
            - path: "/"
              backend:
                service:
                  name: "ph-ee-identity-account-mapper"
                  port:
                    number: 80

