ph-ee-g2psandbox:
  ph-ee-engine:
   
    zeebe-cluster-helm:
      enabled: true

      elasticsearch:
        enabled: false
      kibana:
        enabled: true

    zeebe-operate-helm:
      ingress:
        enabled: true 
        host: operate.sandbox.fynarfin.io 
      
    kibana:
      ingress:
        enabled: true
        className: "nginx"
        pathtype: "Prefix"
        annotations: {}
        # kubernetes.io/ingress.class: nginx
        # kubernetes.io/tls-acme: "true"
        hosts:
          - host: analytics.sandbox.fynarfin.io
            paths:
              - path: /

    operations:
      
    ph_ee_connector_ams_mifos:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-ams-mifos:latest
      imageTag: v1.2.2
      deployment:
        annotations:
          rollme: '{{ randAlphaNum 5 | quote }}'
      ams_local_interop_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_account_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_customer_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_auth_host: "https://fynams.sandbox.fynarfin.io/"
      ams_local_loan_host: "https://fynams.sandbox.fynarfin.io/"
      ingress:
        enabled: true 
        hosts:
          - host: ams-mifos.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: ph-ee-connector-ams-mifos
                  port:
                    number: 80
          - host: ams-mifos-mock.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: ph-ee-connector-ams-mifos
                    port:
                      number: 7070

    ph_ee_connector_mojaloop:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-mojaloop:latest
      imageTag: "830df54849"
      switch:
        quotes:
          host: "http://quoting-service.sandbox.fynarfin.io"
          service: "quoting-service.sandbox.fynarfin.io"
        als:
          host: "http://account-lookup-service.sandbox.fynarfin.io"
          service: "account-lookup-service.sandbox.fynarfin.io"
        transfers:
          host: "http://ml-api-adapter.sandbox.fynarfin.io"
          service: "api-adapter.sandbox.fynarfin.io"
        transactions:
          host: "http://ml-api-adapter.sandbox.fynarfin.io"
          service: "ml-api-adapter.sandbox.fynarfin.io"
        oracle:
          host: "http://moja-simulator.sandbox.fynarfin.io"
      deployment:
        extraEnvs:
          - name: parties_0_domain
            value: "https://fynams.sandbox.fynarfin.io/"
          - name: parties_1_domain
            value: "mojaloop.sandbox.fynarfin.io"
          - name: parties_0_tenantId
            value: "gorilla"
          - name: parties_1_tenantId
            value: "lion"
          - name: parties_0_fspId
            value: "payerfsp"
          - name: parties_1_fspId
            value: "payeefsp"

      ingress:
        enabled: true
        tls:
          - secretName: fyn-cert
        hosts:
          - host: mojaloop.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: ph-ee-connector-mojaloop-java
                  port:
                    number: 80

    # kafka:

    channel:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-channel:latest
      server:
        ssl:
          keyPassword: "password"
          keyStorePassword: "password"   
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      service:
        annotations:
          konghq.com/protocol: "https"
      ingress:
        enabled: true 
        className: "kong"
        hosts:
          - host: channel.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-channel"
                  port:
                    number: 8443
          - host: channel-gsma.sandbox.fynarfin.io          
            paths:          
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-channel-gsma"
                  port:
                    number: 82  
             

    operations_app:
      enabled: true
      image: docker.io/openmf/ph-ee-operations-app:latest
      tenants: "rhino,gorilla"
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      ingress:
        enabled: true 
        hosts:
          - host: ops-bk.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-operations-app"
                  port:
                    number: 80 

    operations_web:
      enabled: true
      image: docker.io/openmf/ph-ee-operations-web:latest
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
        hosts:
          - host: ops.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-operations-web"
                  port:
                    number: 4200
      backend:
        PH_OPS_BACKEND_SERVER_URL: https://ops-bk.sandbox.fynarfin.io/api/v1
        PH_VOU_BACKEND_SERVER_URL: https://vouchers.sandbox.fynarfin.io
        PH_ACT_BACKEND_SERVER_URL: https://identity-mapper.sandbox.fynarfin.io
        PH_PLATFORM_TENANT_ID: gorilla
        PH_PLATFORM_TENANT_IDS: gorilla
        PH_REGISTERING_INSTITUTION_ID: 123
      auth:
        PH_AUTH_ENABLED: false
        PH_OAUTH_ENABLED: false
        PH_OAUTH_TYPE: keycloak
        PH_OAUTH_SERVER_URL: http://keycloak.sandbox.fynarfin.io/auth
        PH_OAUTH_REALM: paymenthub
        PH_OAUTH_CLIENT_ID: opsapp
        PH_OAUTH_CLIENT_SECRET: Y2xpZW50Og==
        PH_OAUTH_BASIC_AUTH: true
        PH_OAUTH_BASIC_AUTH_TOKEN: Y2xpZW50Og==
      PH_DEFAULT_LANGUAGE: en
      PH_SUPPORTED_LANGUAGES: en,fr,es

    ph_ee_connector_gsma:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-gsma:latest
      ingress:
        enabled: true  

    ph_ee_connector_slcb:
      enabled: false
    
    mpesa:
      enabled: false
      
    roster_connector:
      enabled: false
      
    paygops_connector:
      enabled: false
      
    notifications:
      enabled: true
      image: docker.io/openmf/ph-ee-notifications:latest
      NOTIFICATION_FAILURE_ENABLED: "false"
      ingress:
        enabled: true 
        hosts:
          - host: notifications.sandbox.fynarfin.io         
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-notifications"
                  port:
                    number: 80 


    connector_bulk:
      enabled: true
      image: docker.io/openmf/ph-ee-bulk-processor:latest
      tenants: "rhino,gorilla"
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      operations_app:
        contactpoint: "https://ops-bk.sandbox.fynarfin.io/"
        endpoints:
          batch_transaction: "/api/v1/batch/transactions"
      identity_account_mapper:
        hostname: "https://identity-mapper.sandbox.fynarfin.io"
      ingress:
        enabled: true
        className: "kong"
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: bulk-connector.sandbox.fynarfin.io     
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-connector-bulk"
                  port:
                    number: 8443   
          
    zeebe_ops:
      enabled: true
      tenants: "rhino,gorilla"
      ingress:
        enabled: true 
        hosts:
          - host: zeebeops.sandbox.fynarfin.io          
            paths: 
            - path: "/"
              backend:
                service:
                  name: "ph-ee-zeebe-ops"
                  port:
                    number: 80

    messagegateway:
      enabled: true
      image: docker.io/openmf/message-gateway:latest
      secret:
        value:
          api_key: "eKiC1_JWdKy7eaTGQFHxXXjXjacr60W9Zntl"
          project_id: "PJ5ff552ce01d2978c"
      ingress:
        enabled: true   
        hosts:
          - host: messagegateway.sandbox.fynarfin.io       
            paths: 
            - path: "/"
              backend:
                service:
                  name: "message-gateway"
                  port:
                    number: 80
                            
    importer_es:
      enabled: true
      image: docker.io/openmf/ph-ee-importer-es:latest

    importer_rdbms:
      enabled: true
      image: docker.io/openmf/ph-ee-importer-rdbms:latest
      aws:
        region: "ap-south-1"
    
    mockpayment:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-mock-payment-schema:latest
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: mockpaymentschema.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-connector-mock-payment-schema"
                    port:
                      number: 8080

    billPay:
      enabled: true
      image: docker.io/openmf/ph-ee-bill-pay:latest
      billpay:
        contactpoint: "https://bill-pay.sandbox.fynarfin.io"
      connector:
        contactpoint: "https://connector.sandbox.fynarfin.io"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: bill-pay.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-connector-bill-pay"
                    port:
                      number: 8080
    crm:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-crm:latest
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        hosts:
          - host: connector-crm.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-connector-crm"
                    port:
                      number: 8080

    wildcardhostname: "*.sandbox.fynarfin.io"
    tls: ""

    post_installation_job: 
      enabled: true

    keycloak:
      enabled: false
      ingress:
        enabled: true 
        rules:
          - host: 'keycloak.sandbox.fynarfin.io'
            paths:
            - path: /
              pathType: Prefix

    
    kong:
      enabled: false
      ingress:
        enabled: true
        hostname: admin-kong.sandbox.fynarfin.io 

    redis:
      enabled: true
      replica:
        replicaCount: 0

    vouchers:
      enabled: true
      image: docker.io/openmf/ph-ee-vouchers:latest

      voucher:
        hostname: "https://vouchers.sandbox.fynarfin.io"

      salting:
        enabled: true

      identity-account-mapper:
        hostname: "https://identity-mapper.sandbox.fynarfin.io"
      operations:
        hostname: "https://ops-bk.sandbox.fynarfin.io"
        endpoints:
          transfers: "/api/v1/transfers?size=1&page=0"

      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: vouchers.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-vouchers"
                    port:
                      number: 80
    connector:
      enabled: true
      image: docker.io/openmf/ph-ee-connector-bulk:latest
      deployment:
        annotations:
          rollme: "{{ randAlphaNum 5 | quote }}"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: nginx
        tls:
          - secretName: sandbox-secret
        hosts:
          - host: connector.sandbox.fynarfin.io
            paths:
              - path: "/"
                backend:
                  service:
                    name: "ph-ee-connector"
                    port:
                      number: 80
    minio:
      enabled: true
      consoleIngress:
        enabled: true
        annotations:
          kubernetes.io/ingress.class: "nginx"
          nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
        hosts:
          - minio-console.sandbox.fynarfin.io
  account_mapper:
    enabled: true
    image: docker.io/openmf/ph-ee-identity-account-mapper:latest
    deployment:
      annotations:
        rollme: "{{ randAlphaNum 5 | quote }}"
    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
      tls:
        - secretName: sandbox-secret
      hosts:
        - host: identity-mapper.sandbox.fynarfin.io
          paths:
            - path: "/"
              backend:
                service:
                  name: "ph-ee-identity-account-mapper"
                  port:
                    number: 80

                  


