apiVersion: v2
name: ph-barebone-minikube
description: PaymentHub EE Barebone minikube Edition

type: application
version: 0.0.0
appVersion: 1.16.0

dependencies:
- name: ph-ee-engine
  repository: https://fynarfin.io/images/ph-ee-engine-0.0.0-SNAPSHOT/
  version: 0.0.0-SNAPSHOT
