ph-ee-engine:
  zeebe-cluster-helm:
    enabled: false

  zeebe-operate-helm:
    enabled: false

  elasticsearch:
    enabled: false

  kibana:
    enabled: true

  operations:
    mysql:
      enabled: false
    enabled: false

  operationsmysql:
    enabled: false

  ph_ee_connector_ams_mifos:
    enabled: false

  ph_ee_connector_mojaloop:
    enabled: false

  kafka:
    enabled: false

  channel:
    enabled: false

  mockpayment:
    enabled: false

  gsmachannel:
    enabled: false

  operations_app:
    enabled: false

  operations_web:
    enabled: true

  ph_ee_connector_gsma:
    enabled: false

  ph_ee_connector_slcb:
    enabled: false

  mpesa:
    enabled: false

  roster_connector:
    enabled: false
    #remove this after updating the env-template chart
    pesacore:
      auth_header: "PaymentHub"

  paygops_connector:
    enabled: false
    #remove this after updating the env-template chart
    paygops:
      authheader: "PaymentHub"

  notifications:
    enabled: false

  connector_bulk:
    enabled: false

  zeebe_ops:
    enabled: false

  messagegateway:
    enabled: false

  importer_es:
    enabled: false

  importer_rdbms:
    enabled: false

  kong:
    enabled: false

  keycloak:
    enabled: false

  zeebe-operate:
    enabled: false

  mock-oracle:
    enabled: false

  redis:
    enabled: false

fin-engine:
  communityapp:
    enabled: true
  fineract:
    enabled: false
  mariadb:
    enabled: false

operations:
  grafana:
    enabled: true
  prometheus:
    enabled: false