apiVersion: v2
name: back-end
description: A Helm chart for front-end services
type: application
version: 1.0.0
appVersion: "ph-ee-superset: v1.16.0; ph-ee-engine:v1.16.0; fin-engine: v1.0.0; operations: 1.0.0;"

dependencies:
- name: ph-ee-engine
  repository: "https://fynarfin.io/images/ph-ee-engine-1.7.2-SNAPSHOT/"
  version: 1.7.2-SNAPSHOT
  condition: "ph-ee-engine.enabled"
- name: fin-engine
  repository: "https://fynarfin.io/images/fineract/"
  version: 1.0.0-SNAPSHOT
  condition: "fin-engine.enabled"
- name: operations
  repository: "https://fynarfin.io/images/operations/"
  version: "0.1.0"
  condition: "operations.enabled"
