apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: in01tn01-ph-ee-connector-mojaloop-java
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: in01tn01.mifos.io
      http:
        paths:
        - backend:
            serviceName: ph-ee-connector-mojaloop-java-svc
            servicePort: 80
