apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-importer-rdbms
  labels:
    app: ph-ee-importer-rdbms
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-importer-rdbms
  template:
    metadata:
      labels:
        app: ph-ee-importer-rdbms
    spec:
      containers:
        - name: ph-ee-importer-rdbms
          image: paymenthubee.azurecr.io/phee/importer-rdbms
          ports:
            - containerPort: 8000

---
kind: Service
apiVersion: v1
metadata:
  name: ph-ee-importer-rdbms
spec:
  selector:
    app: ph-ee-importer-rdbms
  ports:
    - protocol: TCP
      port: 8000

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ph-ee-operator
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: large-dfsp-operator
      http:
        paths:
          - backend:
              serviceName: ph-ee-importer-rdbms
              servicePort: 8000