apiVersion: apps/v1
kind: Deployment
metadata:
  name: ph-ee-operations-web
  labels:
    app: ph-ee-operations-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ph-ee-operations-web
  template:
    metadata:
      labels:
        app: ph-ee-operations-web
    spec:
      containers:
        - name: ph-ee-operations-web
          image: paymenthubee.azurecr.io/phee/operations-web
          ports:
            - containerPort: 4200
          volumeMounts:
            - name: ph-ee-operations-web-config
              mountPath: "/app/src/assets/configuration.properties"
              subPath: "configuration.properties"
      volumes:
        - name: ph-ee-operations-web-config
          configMap:
            name: ph-ee-operations-web-config

---
apiVersion: v1
data:
  configuration.properties: |
    oauth.enabled true
    oauth.basicAuth true
    oauth.basicAuthToken Y2xpZW50Og==
    oauth.serverUrl http://identity-provider.mifos.io
    serverUrl http://large-dfsp-operator.mifos.io
kind: ConfigMap
metadata:
  name: ph-ee-operations-web-config

---
kind: Service
apiVersion: v1
metadata:
  name: ph-ee-operations-web
spec:
  selector:
    app: ph-ee-operations-web
  ports:
    - protocol: TCP
      port: 4200

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ph-ee-operations-web
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
spec:
  rules:
    - host: buffalo-operations.mifos.io
      http:
        paths:
          - backend:
              serviceName: ph-ee-operations-web
              servicePort: 4200
