apiVersion: v2
name: ph-ee-zeebe-test
description: PaymentHub EE Barebone Edition

type: application
version: 0.2.0
appVersion: 1.16.0

dependencies:
- name: ph-ee-engine
  repository: https://fynarfin.io/images/
  version: 0.0.0-SNAPSHOT
